### ISSUE TITLE
LUA error Started today.

### ISSUE THREAD

**Issue by thesunnymachine** [jordonwow/bigdebuffs#426]
Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:874: attempt to call method 'GetParent' (a nil value)
Time: Sat Oct 29 11:56:49 2022
Count: 1
Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:874: attempt to call method 'GetParent' (a nil value)
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:874: in function `AttachUnitFrame'
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1065: in function `?'
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by carbohydrate** [comment]
Are you on classic / BC / Wrath by chance?

**Comment by Zaeyne** [comment]
Not OP, but I am getting this same error in Wrath.

**Comment by kevsboomba** [comment]
Same here, In WOTLK.

**Comment by kevsboomba** [comment]
Get it on login each time, by the way.

**Comment by kevsboomba** [comment]
I do not play in an arena team. I an not in a group when this happens. It happens on every toon I have including low level ones. The 427 solution is no solution and not relevant.

**Comment by kevsboomba** [comment]
Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:874: attempt to call method 'GetParent' (a nil value)
Time: Tue Nov  1 12:33:21 2022
Count: 1
Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:874: attempt to call method 'GetParent' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:874: in function `AttachUnitFrame'
[string "@Interface\AddOns\BigDebuffs\BigDebuffs.lua"]:1065: in function `?'
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\BagSync\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ce\AddOns\BagSync\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>


I love this addon, but the error is with this addon. If this keeps happening I cannot use it and will be sad.

**Comment by thesunnymachine** [comment]
> I do not play in an arena team. I an not in a group when this happens. It happens on every toon I have including low level ones. The 427 solution is no solution and not relevant.

If you need this addon to work right now you can manually fix it by copying the code from this page https://github.com/carbohydrate/bigdebuffs/commit/b6b61028c935ec57ba9839555bd0048353c3f9e9

Copy 852 - 853

  if k == "Blizzard" then
                        anchor = type(v.units[unit]) == "string" and _G[v.units[unit]] or v.units[unit]
                    if k == "Blizzard" and type(v.units[unit]) == "table" then
                        anchor = v.units[unit]
                        
 make sure to keep everything under starting with 
                        else
                        anchor = _G[v.units[unit]]
 
 Go to the very last line which should now be 2375 and add 'end' (without quotes). 
 
 This will remove the LUA error.

**Comment by kevsboomba** [comment]
TYVM! Sent from Mail for Windows From: carbohydrateSent: Tuesday, November 1, 2022 12:42 PMTo: jordonwow/bigdebuffsCc: kevsboomba; CommentSubject: Re: [jordonwow/bigdebuffs] LUA error Started today. (Issue #426) This has nothing to do with if you are on an arena team or in a group or your level.The fix has not been pushed out to curseforge yet, so you don't have it.If it's still broken when fix is pushed out, I'll take another look—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by kevsboomba** [comment]
TYVM!  Sent from Mail for Windows From: thesunnymachineSent: Tuesday, November 1, 2022 2:24 PMTo: jordonwow/bigdebuffsCc: kevsboomba; CommentSubject: Re: [jordonwow/bigdebuffs] LUA error Started today. (Issue #426) I do not play in an arena team. I an not in a group when this happens. It happens on every toon I have including low level ones. The 427 solution is no solution and not relevant.If you need this addon to work right now you can manually fix it by copying the code from this page ***@***.*** 852 - 853if k == "Blizzard" thenanchor = type(v.units[unit]) == "string" and _G[v.units[unit]] or v.units[unit]if k == "Blizzard" and type(v.units[unit]) == "table" thenanchor = v.units[unit]make sure to keep everything under starting withelseanchor = _G[v.units[unit]]Go to the very last line which should now be 2375 and add 'end' (without quotes).This will remove the LUA error.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
