### ISSUE TITLE
Flame Shock not show party frames 10.0.2

### ISSUE THREAD

**Issue by neuvo123** [jordonwow/bigdebuffs#519]
Hi, the shaman spell flame shock stopped showing on party frames after latest update 10.0.2

Would like to see it to dispel for it, couldnt find it in the spell lists either and it used to show as default on party frames before this 10.0.2

**Comment by j-ogas** [comment]
You can add missing spells you want to track by editing the spell list. I myself prefer to track Deathmark, Exsanguinate, and Feral Frenzy because I can dispel them cauterizing flame.

See https://github.com/jordonwow/bigdebuffs/issues/198 for instructions but do note that the file you need to edit is `BigDebuffs_Mainline.lua`. You may need to update this file again on future updates; it will surely be overwritten.

**Comment by neuvo123** [comment]
I noticed some of the updates had ticked the option for raid frames called "Hide Other Debuffs" which were hideing all the default blizz conditions like flame shock slaughterhouse and dots etc
