### ISSUE TITLE
Poisons/Diseases still showing up for shamans even with 'Only Display Dispellable Debuffs' Checked.

### ISSUE THREAD

**Issue by crossfactioninstancedpvp** [jordonwow/bigdebuffs#736]
![image](https://github.com/jordonwow/bigdebuffs/assets/170687628/29c2e663-8ec1-4141-9665-bf2a8829359b)

![image](https://github.com/jordonwow/bigdebuffs/assets/170687628/ebdc321f-1528-4cd4-91f4-cae7657731b5)

Poison effect showing on me with that option enabled, thank you

**Comment by Somatics23** [comment]
Could this be because I’m playing dwarf? I think poisons and diseases are showing up on my ally as well though. If it is because I’m dwarf, I suggest overriding stoneform as a ‘dispel’ somehow. I only want to see curses/cc on raid frames on my shaman LOL thanks again for the frequent fixes and updates.
